# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 07:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_app', '0002_auto_20170601_0709'),
    ]

    operations = [
        migrations.CreateModel(
            name='FL_freq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_freq', models.FloatField()),
                ('min_freq', models.FloatField()),
            ],
        ),
    ]
